[project]
name = "innowisesolutionsapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.1.1",
    "djangorestframework>=3.18.1",
    "djoser>=2.3.4",
    "gunicorn>=26.2.0",
    "psycopg>=3.3.6",
    "psycopg2-binary>=2.9.13",
    "python-dotenv>=1.2.3",
]
